### ISSUE TITLE
Update for compatibility with josdk v5 and fabric8 v7

### ISSUE THREAD

**Issue by ebma16** [operator-framework/josdk-spring-boot-starter#189]
The recent releases of **JOSDK v5.0.0-beta1** and **Fabric8 Kubernetes Client v7.0.0** introduced changes that make the current josdk-spring-boot-starter incompatible with these versions.

To restore compatibility, an update of this project is required. I have made local changes and performed tests that allow the starter to work correctly with the latest versions of both JOSDK and Fabric8.

**Proposed Solution**
The attached patch resolves the compatibility issues and updates the starter to support the new versions:
Patch: [Update_josdk-spring-boot-starter_for_compatibility_with_JOSDK_v5_and_Fabric8_v7.patch](https://github.com/user-attachments/files/18048884/Update_josdk-spring-boot-starter_for_compatibility_with_JOSDK_v5_and_Fabric8_v7.patch)

Best regards
Martin

**Comment by ebma16** [comment]
Created this [PR](https://github.com/operator-framework/josdk-spring-boot-starter/pull/191) based on the referenced patch as a possible solution

**Comment by heruan** [comment]
Does this include also updating [Spring Boot to 3.4.0](https://github.com/spring-projects/spring-boot/releases/tag/v3.4.0)? Spring Boot 3.4.0 is required to use [Spring Cloud 2024.0.0](https://github.com/spring-cloud/spring-cloud-release/releases/tag/v2024.0.0).

**Comment by csviri** [comment]
Ahh unfrtunally not, but we can do a patch release for that. If you have the bandwidth pls issue a pr.

**Comment by ebma16** [comment]
Here's a [PR proposal](https://github.com/operator-framework/josdk-spring-boot-starter/pull/192) for the SpringBoot v3.4.0 update.

**Comment by ebma16** [comment]
Hi @csviri,
Thank you for merging the Spring Boot PR! Would it be possible to create a patch release for the beta version that includes the Spring Boot update?

It seems the GitHub [workflow on the main branch](https://github.com/operator-framework/josdk-spring-boot-starter/actions/runs/12274981075) failed earlier today when releasing the snapshot, likely due to the major outage at _oss.sonatype.org_. You might need to retrigger the workflow to get it running again.

Thank you so much!

Kind regards
Martin

**Comment by csviri** [comment]
Hi just released it: https://github.com/operator-framework/josdk-spring-boot-starter/releases/tag/6.0.0-beta2

**Comment by ebma16** [comment]
Hi @csviri,

I’m having trouble locating version **6.0.0-beta2** in your Maven repository. Upon checking the “[Release to Maven Central](https://github.com/operator-framework/josdk-spring-boot-starter/actions/runs/12284491016/job/34280366504)” workflow, it seems that a version **.0.0-beta2** was published instead. Could you confirm if something went wrong during the release process?

Thank you so much for your help!

![image](https://github.com/user-attachments/assets/6203a237-994b-4ef1-8efb-e848b14f705a)

**Comment by csviri** [comment]
uhh, sorry, something might went wrong with release process, if you can take a look pls do, otherwise I will tomorrow

**Comment by csviri** [comment]
I see, the tag did not have the proper prefix

**Comment by csviri** [comment]
created a new release, should be in mvn central in 1-2 hours
