### ISSUE TITLE
Mock Kubernetes server doesn't handle resource updates properly

### ISSUE THREAD

**Issue by vadeg** [operator-framework/josdk-spring-boot-starter#4]
Create the following integration test

* Create custom CRD
* Add custom controller
* Create resource. Controller should handle the resource creation event.
* Update or delete resource.  

On the last step controller will not get the resource update / delete event. This happens because of two things:

1. All operator sdk controllers by default use `generation` metadata property to decide what to do with resource event. There is a function called [CustomResourceEventSource.skipBecauseOfGeneration](https://github.com/java-operator-sdk/java-operator-sdk/blob/master/operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/internal/CustomResourceEventSource.java#L148), which rejects events with a generation lower or equal to existing one.
2. [KubernetesCrudDispatcher. setDefaultMetadata](https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-server-mock/src/main/java/io/fabric8/kubernetes/client/server/mock/KubernetesCrudDispatcher.java#L428) from [fabric8io/kubernetes-client](https://github.com/fabric8io/kubernetes-client) library never increase the `generation` property.

Only if to set `@Controller(generationAwareEventProcessing = false)` then update events will reach out to controller. 
I think the MockServer should be updated to be in sync with a default Controller settings.

**Comment by m-kay** [comment]
I can not reproduce this issue anymore in version 5.2.0. 

Not sure how exactly did you update your resource.  When retrieving the current resource via `KubernetesClient` and then using the `patch()` method, it all works fine for me.

This looks as following in my test:
```kotlin
val myResources = kubernetesClient.resources(MyResource::class.java)
myResources.load(ClassPathResource("test-resource.yaml").inputStream).create()

await atMost Duration.ofSeconds(5) until {
    myResources.withName("my-resource").get().status?.observedGeneration == 1L
}

val resource = myResources.withName("my-resource").get()
resource.spec.version = "1.3.3"
myResources.resource(resource).patch()
await atMost Duration.ofSeconds(5) until {
    myResources.withName("my-resource").get().status?.observedGeneration == 2L
}
```

**Comment by csviri** [comment]
great, thank you @m-kay , probably was fixed in fabric8 client, will close the issue!
